import Layout from '@/components/Layout/Layout'
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { FC, ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type RootLayoutDashboardProps = {
  children: ReactNode
}
const RootLayoutDashboard: FC<RootLayoutDashboardProps> = ({ children }) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeRegistry>
            <Layout>{children}</Layout>
          </ThemeRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}

export default RootLayoutDashboard
